name: table_extraction
on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Login Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USER_NAME}}
        password: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}


    # - name: Install black & isort
    #   run: |
    #     pip install black
    #     pip install isort
    #     black .
    #     isort .
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     export PYTHONPATH=.
    #     if [ -f setup.txt ]; then pip install -r setup.txt; fi